### ISSUE TITLE
“Number text field convenience” section

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/human-interface-guidelines-extras#8]
Is there a reason not to use a [stepper](https://developer.apple.com/design/human-interface-guidelines/macos/selectors/steppers/) for this kind of UI element?

**Comment by sindresorhus** [comment]
Good point. Updated: https://github.com/sindresorhus/human-interface-guidelines-extras#number-text-field-convenience Let me know if anything else there could be improved.
